### Creating a new person (POST request)
POST http://127.0.0.1:5003/api
Content-Type: application/json

{
    "name": "John Doe"
}                                                    
### Retrieving a person by Slack Name (GET request)
GET http://127.0.0.1:5003/api?slack_name=backendbro             
### Updating a person by Slack Name (PUT request)
PUT http://127.0.0.1:5003/api?slack_name=backendbro
Content-Type: application/json

{
    "name": "New Name for John Doe"
}

### Deleting a person by Slack Name (DELETE request)
DELETE http://127.0.0.1:5003/api?slack_name=backendbro
